version: '2'

services:
  web2py:
    build: .
    image: daviga/web2py
    command: uwsgi
    environment:
      - WEB2PY_PASSWORD=1234
      - WEB2PY_ADMIN_SECURITY_BYPASS=true
    volumes:
     - web2pyd:/opt/web2py/applications
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./keys:/keys:ro
    depends_on:
      - web2py

    ports:
      - 8080:80
      - 8443:443

volumes:
  web2pyd: 
    external: True
      